# Generated by Django 2.2.5 on 2019-09-13 19:06

from django.db import migrations
import pandas as pd


class Migration(migrations.Migration):

    def import_data(apps, schema_editor):
        performance_metric = apps.get_model('statistics_api', 'PerformanceMetric')
        sample_dataset_df = pd.read_csv('dataset.csv', sep=',')
        performance_metric_data = []
        for row in sample_dataset_df.index:
            performance_metric_data.append(performance_metric(
                date=sample_dataset_df.ix[row]['date'],
                channel=sample_dataset_df.ix[row]['channel'],
                country=sample_dataset_df.ix[row]['country'],
                os=sample_dataset_df.ix[row]['os'],
                impressions=sample_dataset_df.ix[row]['impressions'],
                clicks=sample_dataset_df.ix[row]['clicks'],
                installs=sample_dataset_df.ix[row]['installs'],
                spend=sample_dataset_df.ix[row]['spend'],
                revenue=sample_dataset_df.ix[row]['revenue'],
            ))
        performance_metric.objects.bulk_create(performance_metric_data)

    dependencies = [
        ('statistics_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_data)
    ]
